"""create parent chunks

Revision ID: d8b632ce82f1
Revises: 
Create Date: 2026-09-06 02:45:29.460909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8b632ce82f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('sentence_indices', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_parent_chunks_video_id'), 'parent_chunks', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parent_chunks_video_id'), table_name='parent_chunks')
    op.drop_table('parent_chunks')
    # ### end Alembic commands ###
